### ISSUE TITLE
SQL 執行

### ISSUE THREAD

**Issue by azole** [SaladHsieh/node-workshop#4]
https://github.com/SaladHsieh/node-workshop/blob/09b5c90d0dfd08884534a8ac4b7dde7e6f85f456/crawler/crawler-db.js#L75

請問這句 SQL 在你的 mysql 是可以執行的嗎？因為在我這邊會遇到錯誤，所以確認一下。

**Comment by SaladHsieh** [comment]
老師，抱歉，我測試完成後想起IGNORE可以避免重複新增資料，就加進去code了，還加錯位置T T。剛才push了修正版，下次會注意，有什麼更動都要測試一下再push，謝謝老師!!

**Comment by azole** [comment]
是的，未來職場上要記得，一定一定自己要測試過才可以推，有 bug 事小，萬一壞掉的地方會影響到其他同事的工作進程，那會被大扣分喔...

改好就關掉吧。

**Comment by SaladHsieh** [comment]
是的，我完全了解，謝謝老師!!
